### PR TITLE
added null test for eval function

### PR DESCRIPTION
**Pull request by Stefan-Mitic**
- currently catches the error
- there is a problem with the import statement files.greenberry as tests are not able to run properly, I am not sure about this fix.
- next step: fix errors and add more tests

### CODE REVIEW

**Comment by Abdur-rahmaanJ** [comment]
> there is a problem with the import statement files

more details ^^_

**Comment by Stefan-Mitic** [comment]
line 2, in <module> from files.greenBerry import greenBerry_eval
builtins.ModuleNotFoundError: No module named 'files'

^^ this is the error I am getting, cannot find the module

**Comment by Abdur-rahmaanJ** [comment]
where did you get the files mention, effectively, it does not exist

**Comment by Stefan-Mitic** [comment]
it was from the code before hand, I was able to fix the issue with pull request #43

**Pull request merged**
